// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using nstugram1._1.Context;

namespace nstugram1._1.Migrations
{
    [DbContext(typeof(NstugramContext))]
    partial class NstugramContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("nstugram1._1.Models.Comment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("body");

                    b.Property<long>("idOwner");

                    b.Property<long>("idPhoto");

                    b.Property<int>("likes");

                    b.Property<long>("replyId");

                    b.Property<long>("timeCreated");

                    b.HasKey("id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("nstugram1._1.Models.Following", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("idWhichFollow");

                    b.Property<long>("idWhoFollow");

                    b.HasKey("id");

                    b.ToTable("Followings");
                });

            modelBuilder.Entity("nstugram1._1.Models.Like", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("idOwner");

                    b.Property<long>("idPhoto");

                    b.Property<long>("timeCreated");

                    b.HasKey("id");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("nstugram1._1.Models.Photo", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("alt");

                    b.Property<long>("idOwner");

                    b.Property<int>("likes");

                    b.Property<string>("path");

                    b.Property<long>("timeCreated");

                    b.HasKey("id");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("nstugram1._1.Models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("password");

                    b.Property<long>("timeCreated");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
